profiles/urls.py
from django.urls import path

from . import views

urlpatterns = [

    path(
        route='signup/',
        view=views.SignupUserView.as_view(),
        name='signup'),

    path(
        route='login/',
        view=views.LoginUserView.as_view(),
        name='login'),
        
    path(
        route='logout/',
        view=views.LogoutUserView.as_view(),
        name='logout'),
]

python_assessment/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='/videos/', permanent=True)),
    path('videos/', include(('videos.urls', 'videos'),namespace='videos')),
    path('admin/', admin.site.urls),
    path('users/',include(('profiles.urls', 'profiles'),namespace='profiles')),

]

videos/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path(
        route='',
        view=views.VideoListView.as_view(),
        name='list'),

    path(
        route='popular/',
        view=views.Top5VideoListView.as_view(),
        name='popular'),

    path(
        route='history/',
        view=views.VideoHistory.as_view(),
        name='history'),

    path(
        route='<slug:slug>/',
        view=views.VideoDetailView.as_view(),
        name='detail'),

    path(
        route='<str:youtube_id>/like',
        view=views.like_video,
        name='likes_video'
    ),

    path(
        route='<str:youtube_id>/dislike',
        view=views.dislike_video,
        name='dislikes_video'
    ),

    path(
        route='<str:youtube_id>/comment',
        view=views.comment_video,
        name='comment_video'
    ),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Youtube Clone{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link rel="stylesheet" href="{% static 'admin/css/custom.css' %}">
    {% block extra_head %}{% endblock %}
</head>
<body>
    {% include 'nav.html' %}
    <div class="container mt-5">
        {% block container %}{% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    {% block scripts %}{% endblock %}
</body>
</html>

templates/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    
    <a class="navbar-brand" href="{% url 'videos:list' %}">
        YOUTUBE
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'videos:popular' %}">Popular</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'videos:history' %}">History</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'profiles:logout' %}">Logout</a>
            </li>
            <li class="nav-item">
                <span class="nav-link">Hello {{ user.username }}</span>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'profiles:login' %}">Login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'profiles:signup' %}">Signup</a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>