python_assessment/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='/videos/', permanent=True)),
    path('videos/', include(('videos.urls', 'videos'),namespace='videos')),
    path('admin/', admin.site.urls),
    path('users/',include(('profiles.urls', 'profiles'),namespace='profiles')),

]

videos/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path(
        route='',
        view=views.VideoListView.as_view(),
        name='list'),

    path(
        route='popular/',
        view=views.Top5VideoListView.as_view(),
        name='popular'),

    path(
        route='history/',
        view=views.VideoHistory.as_view(),
        name='history'),

    path(
        route='<slug:slug>/',
        view=views.VideoDetailView.as_view(),
        name='detail'),

    path(
        route='<str:youtube_id>/like',
        view=views.like_video,
        name='likes_video'
    ),

    path(
        route='<str:youtube_id>/dislike',
        view=views.dislike_video,
        name='dislikes_video'
    ),

    path(
        route='<str:youtube_id>/comment',
        view=views.comment_video,
        name='comment_video'
    ),
]

videos/models.py
from django.db import models

from django.contrib.auth.models import User
import datetime

# Create your models here.

class Video(models.Model):
    
    title = models.CharField(
        max_length=256, 
        null=False
    )

    views = models.IntegerField(null=False, default=0)

    author = models.CharField(max_length=200)

    youtube_id = models.CharField(max_length=50, null=False)

    thumbnail_url = models.URLField(max_length=200)

    slug = models.SlugField(max_length=200,unique=True)

    likes = models.ManyToManyField(User)

    dislikes = models.ManyToManyField(
        User, 
        related_name='dislike_videos'
    )

    created_at = models.DateField(default=datetime.date.today)

    comments = models.ManyToManyField(
        User, 
        through='Comment',
        related_name='comments_videos'
    )

    active = models.BooleanField(default=True)

    def __str__(self):
        return '{} by {}'.format(self.title, self.author)

class Comment(models.Model):

    video = models.ForeignKey(Video, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    comment = models.CharField(max_length=300, null=False)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    

videos/views.py
from django.shortcuts import render, redirect
from django.db.models import Count, F, Case, When, IntegerField
from django.urls import reverse_lazy
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, DetailView, View
from django.views.decorators.http import require_http_methods
from django.core import serializers
import datetime
from .models import Video, Comment
from profiles.models import UserHistory

class VideoListView(ListView):
    model = Video
    template_name = "videos/list.html"
    paginate_by = 12

    def get_queryset(self):
        return Video.objects.order_by('?')

class VideoHistory(ListView):
    model = Video
    template_name = "videos/list.html"
    paginate_by = 10

    def get(self, request, *args, **kwargs):
        history = []
        if not request.user.is_anonymous:
            user = request.user
            history = UserHistory.objects.get(user=user)
        else:
            raise Http404("Please log in")            

        self.object_list = self.get_queryset().filter(pk__in=history.history.all())
        allow_empty = self.get_allow_empty()

        if not allow_empty:
            if self.get_paginate_by(self.object_list) is not None and hasattr(self.object_list, 'exists'):
                is_empty = not self.object_list.exists()
            else:
                is_empty = not self.object_list
            if is_empty:
                raise Http404(_("Empty list and '%(class_name)s.allow_empty' is False.") % {
                    'class_name': self.__class__.__name__,
                })
        context = self.get_context_data()
        return self.render_to_response(context)

class Top5VideoListView(ListView):
    model = Video
    template_name = "videos/list.html"
    paginate_by = 10

    def get(self, request, *args, **kwargs):
        self.object_list = self.get_queryset().annotate(
            likes_count=Count('likes')).annotate(
                comments_count=Count('comments')).annotate(
                    dislikes_count=Count('dislikes')).annotate(
                        is_today=Case(When(created_at__gte=datetime.date.today(), then=1), When(created_at__lt=datetime.date.today(), then=0),output_field=IntegerField(),)).annotate(
                            popularity=F('likes_count')*10 + F('comments_count') - F('dislikes_count')*5 + F('is_today')*100).order_by('-popularity')[:5]
        allow_empty = self.get_allow_empty()

        if not allow_empty:
            if self.get_paginate_by(self.object_list) is not None and hasattr(self.object_list, 'exists'):
                is_empty = not self.object_list.exists()
            else:
                is_empty = not self.object_list
            if is_empty:
                raise Http404(_("Empty list and '%(class_name)s.allow_empty' is False.") % {
                    'class_name': self.__class__.__name__,
                })
        context = self.get_context_data()
        return self.render_to_response(context)

class VideoDetailView(DetailView):
    model = Video
    template_name = "videos/detail.html"
    query_set = Video.objects.all()
    slug_field = "slug"
    slug_url_kwarg = "slug"

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)

        # Add to user history
        if not request.user.is_anonymous:
            try:
                hist = UserHistory.objects.get(user=request.user)
                hist.history.add(self.object)
                hist.save()
            except:
                pass

        return self.render_to_response(context)

    def get_context_data(self, **kwargs):
        ContextOfTheView = super().get_context_data(**kwargs)

        video = self.get_object()

        likes = Video.objects.filter(youtube_id=video.youtube_id).aggregate(dislikes_count=Count('dislikes'), likes_count=Count('likes'))

        ContextOfTheView["comments"] = Comment.objects.filter(video=video)
        ContextOfTheView["likes"] = likes
        return ContextOfTheView

    def render_to_response(self, context, **response_kwargs):
        video = self.get_object()
        video.views = video.views + 1
        video.save()
        
        return super().render_to_response(context, **response_kwargs)

@require_http_methods(["POST"])
def comment_video(request, youtube_id):
    print("dislike a video")
    user_logged = request.user
    x = Video.objects.get(youtube_id=youtube_id)
    
    comment_req = request.POST.get("comment")
    
    comment = Comment.objects.create(
        video = x,
        user = user_logged,
        comment = comment_req
    )

    return redirect(reverse_lazy("videos:detail", kwargs={"slug": x.slug}))

@require_http_methods(["POST"])
def like_video(request, youtube_id):
    print("Like a video")
    user_logged = request.user

    video = Video.objects.filter(youtube_id=youtube_id).first()

    if not video:
        return JsonResponse({'error': 'invalid video id'}, status=400)

    video.likes.add(user_logged)

    video.save()

    data = {
        "ok": "Like saved"
    }

    return JsonResponse(data)

@require_http_methods(["POST"])
def dislike_video(request, youtube_id):
    print("Dislike a video")
    user_logged = request.user

    video = Video.objects.filter(youtube_id=youtube_id, active=True).first()
    
    if not video:
        return JsonResponse({'error': 'invalid video id'}, status=400)

    video.dislikes.add(user_logged)

    video.save()
   
    data = {
        "ok": "Dislike saved"
    }

    return JsonResponse(data)

videos/templates/videos/detail.html
{% extends "base.html" %}

{% block container %}

    <div class="row mt-5">
        <div class="col-sm-8 offset-sm-2">
                <div class="embed-responsive embed-responsive-16by9">
                    <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/{{object.youtube_id}}" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
                </div>
        </div>

        <div class="col-sm-8 offset-sm-2 mt-3">
            <h3>{{object.title}}</h3>
            <span>
                <small>By</small>
                {{object.author}}
            </span>
            <span>{{object.views}} views
            </span>
        </div>

        <div class="col-sm-8 offset-sm-2 mt-3">
            <a class="like">
                <span>{{likes.likes_count}}</span>
                <i class="far fa-thumbs-up"></i>
            </a>
            <a class="dislike">
                <span>{{likes.dislikes_count}}</span>
                <i class="far fa-thumbs-down"></i>
            </a>
        </div>
    </div>

    <div class="row mt-5">
        <div class="col-sm-8 offset-sm-2">
            <form action="{% url 'videos:comment_video' object.youtube_id %}" method="POST" id="comment_video">
                {% csrf_token %}
                <textarea 
                    name="comment" 
                    id="comment" 
                    cols="2" 
                    rows="2" 
                    class="form-control w-100" 
                    required
                    placeholder="Write your comment here..."
                    style="color:black;"
                ></textarea>
                <button class="btn btn-primary mb-2 mt-2" type="submit" {% if not user.is_authenticated  %} disabled {% endif %}>Comment</button>
            </form>
        </div>
    </div>
    
    <div class="row mt-5">
        <div class="col-sm-8 offset-sm-2">
            <h3>Comments: </h3>
            {% for comment in comments %}
                <div class="card w-100 mt-2">
                    <div class="card-body">
                        <h5 class="card-title">By: {{comment.user.username}}</h5>
                        <p class="card-text">{{comment.comment}}</p>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock container %}


{% block scripts %}

<script>
    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    var csrftoken = getCookie('csrftoken');
    function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
    $.ajaxSetup({
        beforeSend: function(xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
        }
    });
    $('.like').click(() => {
        console.log('like')
        $.post("{% url "videos:likes_video" object.youtube_id %}", {}, function(result) {
            console.log(result)
        })
    })

    $('.dislike').click(() => {
        console.log('dislike')
        $.post("{% url "videos:dislikes_video" object.youtube_id %}", {}, function(result) {
            console.log(result)
        })
    })

</script>

{% endblock scripts %}

videos/templates/videos/list.html
{% extends "base.html" %}

{% block container %}

    <div class="container mt-5">
        <h1 class="text-center"></h1>
        <div class="row">
            {% for video in object_list %}
            <div class="col-md-4 mb-4">
                <div class="card h-100">
                    <img src="{{ video.thumbnail_url }}" class="card-img-top" alt="{{ video.title }}">
                    <div class="card-body d-flex flex-column">
                        <h5 class="card-title">{{ video.title }}</h5>
                        <p class="card-text">By: {{ video.author }}</p>
                        <a href="/videos/{{ video.slug }}/" class="btn btn-primary mt-auto">Watch</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        {% if paginator %}
        <div class="row mt-5">
            <div class="col">
                <nav aria-label="Page navigation">
                    <ul class="pagination justify-content-center">
                        {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                        {% endif %}
                        {% for num in paginator.page_range %}
                        {% if page_obj.number == num %}
                        <li class="page-item active"><span class="page-link">{{ num }}</span></li>
                        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                        <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                        {% endif %}
                        {% endfor %}
                        {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
        </div>
        {% endif %}
    </div>

{% endblock container %}